# Generated by Django 4.2.3 on 2023-08-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_video_videoview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VideoView",
        ),
    ]
